version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: projet6_db_symfony
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: symfony_docker
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - projet6

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: projet6_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - projet6

    # Symfony apache project container
    www:
        build: docker/php
        container_name: projet6
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - projet6

networks:
    projet6:

volumes:
    db-data: