controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_page:
    path: /
    controller: App\Controller\HomeController::index

show_trick:
    path: /showTrick
    controller: App\Controller\HomeController::showTrick

trick_page:
    path: /trick/{slug}
    controller: App\Controller\TrickController::index
