<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4w3gSVG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4w3gSVG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4w3gSVG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4w3gSVG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4w3gSVG\App_KernelDevDebugContainer([
    'container.build_hash' => '4w3gSVG',
    'container.build_id' => 'd6231775',
    'container.build_time' => 1705347635,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4w3gSVG');
